name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      #attestations: write
      #id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{  github.repository }}:${{ github.ref_name }}

  cleanup:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04

    needs: [build]

    permissions:
      packages: write

    env:
      VERSIONS_TO_KEEP: 1

    if: success()
    steps:
      - name: Clean up old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: ${{env.VERSIONS_TO_KEEP}}

  notify:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04

    env:
      TEXT: "New image published: ghcr.io/${{  github.repository }}:${{ github.ref_name }}"

    needs: [build]

    if: success()
    steps:
      - name: Post to MS Teams
        run: |
          curl -H 'Content-Type: application/json' -d '{"text":"${{env.TEXT}}"}' ${{ secrets.MS_TEAMS_URL }}
