name: package-cleanup

on:
  registry_package:
    types: [published]

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'provisioning_scripts'
          package-type: 'container'
          min-versions-to-keep: 1
